#!/bin/sh
# (C) 2019 DASAN InfoTek,
#           leesy@DSI
##
. wCommon

DIALOG=${DIALOG=dialog}

tempfile="/tmp/config_NET$$"
trap "rm -f $tempfile; exit" 0 1 2 5 15

textinput() {
	$DIALOG \
	--ascii-lines --title "INPUT BOX" --clear \
	--inputbox "$1" 20 76 "$2" 2> $tempfile

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi

	return $retval
}

menuinput() {

	menucmd=$(cat <<END    
$DIALOG --ascii-lines --clear --cr-wrap --title "[[ Network IP Configurations ]]" \
	--menu "$3\nWLAN=[ $rHWMODE ESSID:$rSSID ] \nStat=[ SNR:$rSNR Freq:$rFreq STAs:$rSTA ] \
	\n$rDATE >> Please menu select: \n" 22 76 11 \
	$1 \
	2> $tempfile
END
)

eval $menucmd

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}


########################## begin

rm -f $tempfile

mchoice="";

while : ; do

	inputvar=""

	readModelName

	readCFG
	#######

	readNET
	#######

	readDATE
	#######

	menuinput '"ReviewSNR_STA"  "Status Review .... Enter!"
		"1eLAN_IPaddr"  "Wired-LAN IP Address ________($cLip)"
		"2eLAN_IPmask"  "Wired-LAN IP Subnet Mask ____($cLmask)"
		"3eLAN_Gateway" "Gateway/Router IP Address ___($cLgway)"
		"4eLAN_IPdns"   "DNS Server IP Address _______($cLdns)"
		"X_ExitCancel"  "Exit or Cancel to upper Menu"'

	case $inputvar in

	ReviewSNR_STA)
		;;

	1eLAN_IPaddr)
		inputvar=$cLip
		errormsg=""
		while :; do
			textinput \
				 "Please enter Wired Ethernet IP Address ...\n\n"$(
				)"Examples:\n"$(
				)" 10.1.123.1  168.126.0.129\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cLip" ] && break
			# Check valid IP v4
			if isValidIPv4 "$inputvar"; then
				uci set network.lan.ipaddr="$inputvar"
				###
				eMAC=$(/sbin/ifconfig | grep "eth0" | tr -s " " | cut -d " " -f5)
				echo "$eMAC $inputvar" > /etc/ethers
				###
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	2eLAN_IPmask)
		inputvar=$cLmask
		errormsg=""
		while :; do
			textinput \
				 "Please enter Wired Ethernet IP Subnet Mask ...\n\n"$(
				)"Examples:\n"$(
				)" 255.255.255.0 255.255.255.128\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cLmask" ] && break
			# Check valid IP v4
			if isValidIPv4 "$inputvar"; then
				uci set network.lan.netmask="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	3eLAN_Gateway)
		inputvar=$cLgway
		errormsg=""
		while :; do
			textinput \
				 "Please enter Network Gateway/Router IP Address\n\n"$(
				)"Examples: can blank\n"$(
				)" 10.1.1.1  192.168.0.1 \n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cLgway" ] && break
			# Check string null or valid IP v4
			if [ -z "$inputvar" ] || isValidIPv4 "$inputvar"; then
				uci set network.lan.gateway="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	4eLAN_IPdns)
		inputvar=$cLdns
		errormsg=""
		while :; do
			textinput \
				 "Please enter Network DNS Server IP Address ...\n\n"$(
				)"Examples: can blank\n"$(
				)" 168.126.63.1  168.126.63.1\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cLdns" ] && break
			# Check string null or valid IP v4
			if [ -z "$inputvar" ] || isValidIPv4 "$inputvar"; then
				uci set network.lan.dns="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	X_ExitCancel | *)
		rm $tempfile >/dev/null 2>/dev/null
		exit 0
		;;

	esac
done
