#!/bin/sh
# (C) 2019 DASAN InfoTek,
#           leesy@DSI
##
. wCommon

DIALOG=${DIALOG=dialog}

tempfile="/tmp/config_main$$"
trap "rm -f $tempfile; exit" 0 1 2 5 15

textinput() {
	$DIALOG \
	--ascii-lines --title "INPUT BOX" --clear \
	--inputbox "$1" 20 76 "$2" 2> $tempfile

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}

menuinput() {

	menucmd=$(cat <<END    
$DIALOG --ascii-lines --clear --cr-wrap --title "[ $ModelName V6.2 Configurations 2019@DSi ]" \
	--menu "$3\nWLAN=[ $rHWMODE ESSID:$rSSID ] \nStat=[ SNR:$rSNR Freq:$rFreq STAs:$rSTA ] \
	\n$rDATE >> Please menu select: \n" 22 76 11 \
	$1 \
	2> $tempfile
END
)

eval $menucmd

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}


########################## begin

rm -f $tempfile

mchoice="";

while : ; do

	sync
	####

	inputvar=""

	readModelName

	readCFG
	#######

	readDATE
	#######

	menuinput '"ReviewSTATs"  "Status Review .... Enter!"
		"1NetIPconfig"   ">> Network TCP/IP Address ___________Configure <<"
		"2WLAN_config"   ">> Wireless LAN Freq, SSID & Secure _Configure <<"
		"3SaveCommit"    "Commit All Configure Save!"
		"4SaveReboot"    "Save(commit) & ReBOOT....!"
		"5JustREBOOT"	 "==============>ReBOOT....!"'

	case $inputvar in

	ReviewSTATs)
		;;

	1NetIPconfig)
		/etc/dwb4054/wNETsetup
		;;

	2WLAN_config)
		/etc/dwb4054/wWIFIsetup
		;;

	3SaveCommit)
		textinput \
			 "Commit All Configures & Save Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no] \n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
			clear
			echo ; echo "[$ModelName].... Commit All Configures Now!!"
			###################################################################
			uci commit
			#sleep 1
			echo ; echo "[$ModelName].... All Interface Restart...!!"
			/etc/init.d/network restart 2>/dev/null
			sleep 1
		fi
		;;

	4SaveReboot)
		textinput \
			 "Commit All Configures & ReBOOT Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no]\n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
			clear
			echo ; echo "[$ModelName].... Commit All Configures Now!!"
			###################################################################
			uci commit
			#sleep 1
			echo ; echo "[$ModelName].... System Reboot Now!!"
			reboot
			while : ; do
				sleep 1
				echo -n "."
			done
		fi
		;;

	5JustREBOOT)
		textinput \
			 "===============> ReBOOT Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no]\n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
		  clear
		  echo ; echo "[$ModelName].... System Reboot Now!!"
		  reboot -f
		  while : ; do
			sleep 1
			echo -n "."
		  done
		fi
		;;

	# *)
	#	rm $tempfile >/dev/null 2>/dev/null
	#	exit 0
	#	;;

	esac

done

sync

rm $tempfile >/dev/null 2>/dev/null
exit 0

