#!/bin/sh
# (C) 2020 DASAN InfoTek
#           leesy@DSI
##
. common

cp /etc/dwsb/dual_sta_roaming.cfg /tmp/dual_sta_roaming.cfg

CONFIGPATH_org="/etc/dwsb/dual_sta_roaming.cfg"
CONFIGPATH="/tmp/dual_sta_roaming.cfg"
CONFIG_UPDATED="/tmp/.dual_sta_roaming.cfg.updated"

save_value() {
	egrep -v '^$' $CONFIGPATH | egrep -v "^"$1 > $CONFIGPATH.new
	echo $1"=\"$inputvar\"" >> $CONFIGPATH.new
	echo >> $CONFIGPATH.new
	rm -f $CONFIGPATH
	mv $CONFIGPATH.new $CONFIGPATH

	cp $CONFIGPATH $CONFIGPATH_org
	sync
}

while : ; do

	readSystem

	CUR_USE_DUALSTAROAM_MODE=$(grep "_USE_DUALSTAROAM_MODE" $CONFIGPATH | sed 's/.*="\(.*\)"/\1/')
	CUR_SNRmin=$(grep "_SNRmin" $CONFIGPATH | sed 's/.*="\(.*\)"/\1/')
	CUR_SNRdelta=$(grep "_SNRdelta" $CONFIGPATH | sed 's/.*="\(.*\)"/\1/')
	CUR_PingIP1=$(grep "_PingIP1" $CONFIGPATH | sed 's/.*="\(.*\)"/\1/')
	CUR_PingIP2=$(grep "_PingIP2" $CONFIGPATH | sed 's/.*="\(.*\)"/\1/')
	CUR_PingTO=$(grep "_PingTO" $CONFIGPATH | sed 's/.*="\(.*\)"/\1/')
	CUR_PingFC=$(grep "_PingFC" $CONFIGPATH | sed 's/.*="\(.*\)"/\1/')

	### echo "($CUR_USE_DUALSTAROAM_MODE) ($CUR_SNRmin) ($CUR_SNRdelta) ($CUR_PingIP1) ($CUR_PingIP2) ($CUR_PingTO) ($CUR_PingFC)"

	inputvar=""

	if [ "$CUR_USE_DUALSTAROAM_MODE" != "Y" ] ; then
		menuinput  "Dual-Station Roaming Configure" \
			'"1_UseDualSta" "Configure to use Dual-Station Roaming mode ($CUR_USE_DUALSTAROAM_MODE)"
			"X_ExitCancel"  "Exit or Cancel to upper Menu"'
	else
		menuinput  "Dual-Station Roaming Configure" \
			'"1_UseDualSta" "Configure to use Dual-Station Roaming mode ($CUR_USE_DUALSTAROAM_MODE)"
			"2_SNRmin"      "Configure Minimum SNR for Roaming ($CUR_SNRmin)"
			"3_SNRdelta"    "Configure Delta SNR for Roaming ($CUR_SNRdelta)"
			"4_PingIP1"     "Configure AP IP to ping for 1st STA ($CUR_PingIP1)"
			"5_PingIP2"     "Configure AP IP to ping for 2nd STA ($CUR_PingIP2)"
			"6_PingTO"      "Configure Time Out to ping AP IP ($CUR_PingTO)"
			"7_PingFC"      "Configure Fail Count to ping AP IP ($CUR_PingFC)"
			"8_TestRoaming" "Test Dual-Station Roaming!"
			"X_ExitCancel"  "Exit or Cancel to upper Menu"'
	fi

	case $inputvar in

	1_UseDualSta)
		inputvar=$CUR_USE_DUALSTAROAM_MODE
		errormsg=""
		while :; do
			textinput \
				"Please enter Y to use Dual-Station Roaming mode otherwise enter N or empty\n"$(
				)"Examples:\n"$(
				)" Y  N\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$CUR_USE_DUALSTAROAM_MODE" ] && break
			# Check string null or Y or N
			([ -z "$inputvar" ] || [ $inputvar = "Y" ] || [ $inputvar = "N" ]) && {
				save_value "_USE_DUALSTAROAM_MODE"
				break
			}
			errormsg="Check input value is Y or N or empty!"
		done
		;;

	2_SNRmin)
		inputvar=$CUR_SNRmin
		errormsg=""
		while :; do
			textinput \
				"Please enter minimum SNR for roaming in NN dBm(0 < NN < 70)\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$CUR_SNRmin" ] && break
			# Check 0 < value < 70
			[ -n "$inputvar" ] && [ $inputvar -gt 0 ] 2>/dev/null && [ $inputvar -lt 70 ] 2>/dev/null && {
				save_value "_SNRmin"
				break
			}
			errormsg="Check input value NN is 0 < NN < 70"
		done
		;;

	3_SNRdelta)
		inputvar=$CUR_SNRdelta
		errormsg=""
		while :; do
			textinput \
				"Please enter delta SNR for roaming in NN dBm(0 <= NN <= 35)\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$CUR_SNRdelta" ] && break
			# Check 0 < value < 70
			[ -n "$inputvar" ] && [ $inputvar -ge 0 ] 2>/dev/null && [ $inputvar -le 35 ] 2>/dev/null && {
				save_value "_SNRdelta"
				break
			}
			errormsg="Check input value NN is 0 <= NN <= 35"
		done
		;;

	4_PingIP1)
		inputvar=$CUR_PingIP1
		errormsg=""
		while :; do
			textinput \
				 "Please enter AP's IP to ping for 1st Station\n"$(
				)" Ping disabled when empty\n\n"$(
				)"Examples: can blank\n"$(
				)" 192.168.0.127  10.1.1.127\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$CUR_PingIP1" ] && break
			# Check string null or valid IP v4
			if [ -z "$inputvar" ] || isValidIPv4 "$inputvar"; then
				save_value "_PingIP1"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	5_PingIP2)
		inputvar=$CUR_PingIP2
		errormsg=""
		while :; do
			textinput \
				 "Please enter AP's IP to ping for 2nd Station\n"$(
				)" Ping disabled when empty\n\n"$(
				)"Examples: can blank\n"$(
				)" 192.168.0.127  10.1.1.127\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$CUR_PingIP2" ] && break
			# Check string null or valid IP v4
			if [ -z "$inputvar" ] || isValidIPv4 "$inputvar"; then
				save_value "_PingIP2"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	6_PingTO)
		inputvar=$CUR_PingTO
		errormsg=""
		while :; do
			textinput \
				"Please enter Time Out to ping AP IP in milli-second(> 0)\n\n"$(
				)"Examples:\n"$(
				)" 1  7  10  20\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$CUR_PingTO" ] && break
			# Check greater than zero
			[ $inputvar -gt 0 ] 2>/dev/null && {
				save_value "_PingTO"
				break
			}
			errormsg="Check input value is greater than 0!"
		done
		;;

	7_PingFC)
		inputvar=$CUR_PingFC
		errormsg=""
		while :; do
			textinput \
				"Please enter Fail Count(0 < c <= 5) to ping AP IP\n"$(
				)" Ping disabled when zero or empty\n\n"$(
				)"Examples:\n"$(
				)" 1  2  3  4  5\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$CUR_PingFC" ] && break
			# Check string null or greater and equal than zero
			([ -z "$inputvar" ] || [ $inputvar -ge 0 ] 2>/dev/null || [ $inputvar -le 5 ] 2>/dev/null) && {
				save_value "_PingFC"
				break
			}
			errormsg="Check input value is empty or greater and equal than 0 and little equal 5 !"
		done
		;;

	8_TestRoaming)
		inputvar="N"
		textinput \
			"Dual-Station Roaming TEST... Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [Y]=Run Roaming/[N]=Exit\n" \
			"$inputvar"
		retval=$?
		# Check return error
		[ $retval -ne 0 ] && break
		[ "$inputvar" = "Y" ] && {
			clear
			echo ; echo "[$cHostname]... Roaming New Station Now!!"
			touch /tmp/.force_Dual_Sta_Roaming
			sleep 1 # sleep 1 second

			local TestRoamingTimer=0
			local TestRoamingTimeout=30 # 30secs
			while [ -e /tmp/.force_Dual_Sta_Roaming ] ; do
				sleep 1 # sleep 1 second
				TestRoamingTimer=$((TestRoamingTimer+1))
				[ $TestRoamingTimer -ge $TestRoamingTimeout ] && break
			done

			if [ -e /tmp/.force_Dual_Sta_Roaming ] ; then
				rm -f /tmp/.force_Dual_Sta_Roaming
				echo ; echo "[$cHostname]... Error! Roaming New Station!"
			else
				echo ; echo "[$cHostname]... Success! Roaming New Station."
			fi

			sleep 1 # sleep 1 second
		}
		;;

	X_ExitCancel | *)
		rm $tempfile >/dev/null 2>/dev/null
		exit 0
		;;
	esac
done
