#!/bin/sh
#
#####################################################################
##
##      DWSB station for Chaos Calmer 15.05.1 @linux3.18
##
##                Copyright 2020, by Dasan InfoTek Co., 
##
##                         ...leesy...
##
#####################################################################

log() {
	##echo "$@"
	echo "$(basename $0): $@" >/dev/kmsg
	##logger -t $(basename $0) "$@"
}

get_actFreqMHz() {
	iw wlan$cStaIndex link 2> /dev/null | grep "freq:" | awk '{ print $2 }'
}

get_curFreqMHz() {
	local ch
	local freq
	ch=$(uci -q get wireless.radio$cStaIndex.channel)
	[ "$ch" = "auto" ] && {
		freq="auto"
	} || {
		[ ! -f /tmp/iw_info_phy$cStaIndex ] && iw phy$cStaIndex info 2>/dev/null > /tmp/iw_info_phy$cStaIndex
		freq=$(grep -E -m1 "(\* .... MHz \[$ch\])" /tmp/iw_info_phy$cStaIndex | \
			awk '{print $2}')
		[ -z "$freq" ] && freq="0000"
	}
	echo $freq
}

### Start of main script

cStaIndex=$1

#sleep 1

# Main infinite loop
# Check and wait actual freq. match with freq. of config.
while : ; do
	curFreqMHz=$(get_curFreqMHz)
	actFreqMHz=$(get_actFreqMHz)

	log "dwsbStation: curFreq=$curFreqMHz, actFreq=$actFreqMHz"

	# Check actual Freq is not null, mean is not equal with current Freq.
	if [ -n "$actFreqMHz" ] && [ "$curFreqMHz" != "auto" ] && [ "$actFreqMHz" != "$curFreqMHz" ]; then
		/etc/init.d/network restart
		sleep 1
	fi

	sleep 1
done

### End of main script
