#!/bin/sh
#
#####################################################################
##
##      DWSB Channel Roaming for Chaos Calmer 15.05.1 @linux3.18
##
##                Copyright 2020, by Dasan InfoTek Co., 
##
##                         ...leesy...
##
#####################################################################

. /etc/dwsb/dwsbChRoaming 0
