#!/bin/sh
#
#####################################################################
##
##DWB4054 Link Integrity Checking for Chaos Calmer 15.05.1 @linux3.18
##
##                Copyright 2021, by Dasan InfoTek Co., 
##
##                         ...leesy...
##
#####################################################################

log() {
	##echo "$@"
	echo "$(basename $0): $@" >/dev/kmsg
	##logger -t $(basename $0) "$@"
}

get_curWiFiMode() {
	local disabled=$(uci -q get wireless.@wifi-iface[$iface_index].disabled)
	local wds=$(uci -q get wireless.@wifi-iface[$iface_index].wds)
	local mode=$(uci -q get wireless.@wifi-iface[$iface_index].mode)
	local ret_mode
	if [ "$disabled" = "1" ]; then
		ret_mode="Disabled"
	else
		if [ "$mode" = "ap" ]; then
			[ "$wds" = "1" ] && {
				ret_mode="APW"
			} || {
				ret_mode="AP"
			}
		elif [ "$mode" = "sta" ]; then
			[ "$wds" = "1" ] && {
				ret_mode="STW"
			} || {
				ret_mode="ST"
			}
		else
			# in case [ "$mode" != "ap" ] && [ "$mode" != "sta" ]
			ret_mode=$mode
		fi
	fi
	echo $ret_mode
}

isWiFiDown() {
	iwinfo wlan$iface_index info > /dev/null 2> /dev/null
	echo $?
}


########################
### Start of main script
########################

iface_index=$1
if [ $iface_index -eq 0 ] ; then
	iface_index_str="1st"
elif [ $iface_index -eq 1 ] ; then
	iface_index_str="2nd"
else
	# in case not [ $iface_index -eq 0 ] || [ $iface_index -eq 1 ]
	log "Interface index($iface_index) is not valid. ---> exit"
	exit 1
fi

### Check WiFi mode is AP (or with WDS)
curWiFiMode=$(get_curWiFiMode)
if [ "$curWiFiMode" != "AP" ] && [ "$curWiFiMode" != "APW" ] ; then
	# in case WiFi mode is not AP
	log "WiFi mode($curWiFiMode) is not AP. ---> exit"
	exit 1
fi

#-----------------------------#
### Load Link Integrity Checking configuration from file
if [ ! -e /etc/dwsb/link_int_checking_$iface_index.cfg ] ; then
	# in case file not exist
	log "File(/etc/dwsb/link_int_checking_$iface_index.cfg) not exist. ---> exit"
	exit 1
fi
. /etc/dwsb/link_int_checking_$iface_index.cfg

USE_LINKINTEGRITYCHECK_MODE=$_USE_LINKINTEGRITYCHECK_MODE
[ "$USE_LINKINTEGRITYCHECK_MODE" != "Y" ] && {
	log "Link Integrity Checking for $iface_index_str AP disabled. ---> exit"
	exit 1
}

PingIP=$_PingIP
[ -z "$_PingCI" ] && PingCI=0 || PingCI=$_PingCI
[ -z "$_PingTO" ] && PingTO=0 || PingTO=$_PingTO
[ -z "$_PingFC" ] && PingFC=0 || PingFC=$_PingFC
#-----------------------------#
log "Ping IP=$PingIP CI="$PingCI"sec TO="$PingTO"msec FC=$PingFC"

rm -f /tmp/.force_LinkErr_$iface_index

#sleep 1

# Init CI count
CntCI=0

# Main infinite loop
while : ; do
	# Check need to test link error
	if [ -e /tmp/.force_LinkErr_$iface_index ] ; then
		log "Forced Down WiFi radio$iface_index !"
		# Get last Wifi up/down status
		local Last_isWiFiDown=$(isWiFiDown)
		# Check WiFi is not down
		if [ $Last_isWiFiDown -eq 0 ] ; then
			wifi down radio$iface_index > /dev/null 2> /dev/null
		fi
		# Wait untit test finished
		while [ -e /tmp/.force_LinkErr_$iface_index ]; do
			sleep 1
		done
		log "Finished Forced Down WiFi radio$iface_index !"
		# Back to last WiFi up/down status
		if [ $Last_isWiFiDown -eq 0 ] ; then
			wifi up radio$iface_index > /dev/null 2> /dev/null
		fi
	fi

	# Check parameters are correct or not
	if [ -z "$PingIP" ] || [ $PingCI -eq 0 ] || [ $PingTO -eq 0 ] || [ $PingFC -eq 0 ]; then
		# Parameters are incorrect
		# Do nothing
		sleep 1
	else # Parameters are correct
		# Sleep 1 sec
		sleep 1
		# Update CI count
		CntCI=$((CntCI+1))

		# Check Sleep CI(Check Interval) secs
		if [ $CntCI -ge $PingCI ]; then
			# Init CI count
			CntCI=0

			# Check remote IP via ping
			#log "Checking remote IP($PingIP)"

			# Init ping fail count(FC)
			curPingFC=0
			# Ping check loop
			while : ; do
				# Check fping return sucess
				fping -4 -b0 -t$PingTO -r1 -q $PingIP && {
					# fping returned success
					#log "Ping success!($PingIP)"
					# Check WiFi is down
					if [ $(isWiFiDown) -eq 1 ] ; then
						log "Ping success!($PingIP) ->"
						log "Up WiFi radio$iface_index !"
						wifi up radio$iface_index > /dev/null 2> /dev/null
					fi
					break
				}

				# fping returned fail
				# log "Ping fail!($curPingFC)"

				# Increase fail count(FC)
				curPingFC=$((curPingFC+1))

				# Check FC is reach the limit
				if [ $curPingFC -ge $PingFC ] ; then
					#log "Ping fail count is over!(($PingIP:$curPingFC)"
					# Check WiFi is not down
					if [ $(isWiFiDown) -eq 0 ] ; then
						log "Ping failed!($PingIP:$curPingFC) ->"
						log "Down WiFi radio$iface_index !"
						wifi down radio$iface_index > /dev/null 2> /dev/null
					fi
					break
				fi

				# Sleep 10 milli-second to stable ping
				msleep 10
			done
		fi
	fi
done

### End of main script
