#!/bin/sh
# (C) 2020 DASAN InfoTek,
#           leesy@DSI
##
. common

DUAL_STA_ROAMING_CONFIG_org="/etc/dwsb/dual_sta_roaming.cfg"
DUAL_STA_ROAMING_CONFIG_tmp="/tmp/dual_sta_roaming.cfg"
CH_ROAMING_0_CONFIG_org="/etc/dwsb/channel_roaming_0.cfg"
CH_ROAMING_0_CONFIG_tmp="/tmp/channel_roaming_0.cfg"
CH_ROAMING_1_CONFIG_org="/etc/dwsb/channel_roaming_1.cfg"
CH_ROAMING_1_CONFIG_tmp="/tmp/channel_roaming_1.cfg"

init_config_org

while : ; do

	inputvar=""

	menuinput "Status Overview" \
		'"ReviewStatus"       "Review Status .... Enter!"
		"1SystemConfig"       ">> Host Name & Date time __________Configure <<"
		"2LanConfig"          ">> LAN Network ____________________Configure <<"
		"3FirstWiFiConfig"    ">> 1st Wireless Network ___________Configure <<"
		"4SecondWiFiConfig"   ">> 2nd Wireless Network ___________Configure <<"
		"5ChRoamFirstConfig"  ">> Channel Roaming 1st Station ____Configure <<"
		"6ChRoamSecondConfig" ">> Channel Roaming 2nd Station ____Configure <<"
		"7DualStaRoamConfig"  ">> Dual-Station Roaming ___________Configure <<"
		"8SaveCommit"         "Commit All Configure Save!"
		"9SaveReboot"         "Save(commit) & ReBOOT....!"
		"0JustREBOOT"         "==============>ReBOOT....!"'

	case $inputvar in

	ReviewStatus)
		;;

	1SystemConfig)
		/etc/dwsb/system
		;;

	2LanConfig)
		/etc/dwsb/net_lan
		;;

	3FirstWiFiConfig)
		/etc/dwsb/net_wifi 0
		;;

	4SecondWiFiConfig)
		/etc/dwsb/net_wifi 1
		;;

	5ChRoamFirstConfig)
		/etc/dwsb/channel_roaming 0
		;;

	6ChRoamSecondConfig)
		/etc/dwsb/channel_roaming 1
		;;

	7DualStaRoamConfig)
		/etc/dwsb/dual_sta_roaming
		;;

	8SaveCommit)
		textinput \
			 "Commit All Configures & Save Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no] \n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
			/etc/init.d/dwsbLCD stop 2>/dev/null
			/etc/init.d/dwsbDualStaRoaming stop 2>/dev/null
			/etc/init.d/dwsbChRoaming_1 stop 2>/dev/null
			/etc/init.d/dwsbChRoaming_0 stop 2>/dev/null

			clear
			echo ; echo "[$aHostname].... Commit All Configures Save Now!!"
			[ -f $DUAL_STA_ROAMING_CONFIG_tmp ] && mv $DUAL_STA_ROAMING_CONFIG_tmp $DUAL_STA_ROAMING_CONFIG_org
			[ -f $CH_ROAMING_0_CONFIG_tmp ] && mv $CH_ROAMING_0_CONFIG_tmp $CH_ROAMING_0_CONFIG_org
			[ -f $CH_ROAMING_1_CONFIG_tmp ] && mv $CH_ROAMING_1_CONFIG_tmp $CH_ROAMING_1_CONFIG_org
			apply_config_new_4_commit
			clean_config_new
			uci commit
			init_config_org

			echo ; echo "[$aHostname].... Restart Network Subsystem ...!!"
			/etc/init.d/network restart
			sleep 5

			/etc/init.d/dwsbChRoaming_0 start 2>/dev/null
			/etc/init.d/dwsbChRoaming_1 start 2>/dev/null
			/etc/init.d/dwsbDualStaRoaming start 2>/dev/null
			/etc/init.d/dwsbLCD start 2>/dev/null
			sleep 5
		fi
		;;

	9SaveReboot)
		textinput \
			 "Commit All Configures & ReBOOT Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no]\n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
			/etc/init.d/dwsbLCD stop 2>/dev/null
			/etc/init.d/dwsbDualStaRoaming stop 2>/dev/null
			/etc/init.d/dwsbChRoaming_1 stop 2>/dev/null
			/etc/init.d/dwsbChRoaming_0 stop 2>/dev/null

			clear
			echo ; echo "[$aHostname].... Commit All Configures Now!!"
			[ -f $DUAL_STA_ROAMING_CONFIG_tmp ] && mv $DUAL_STA_ROAMING_CONFIG_tmp $DUAL_STA_ROAMING_CONFIG_org
			[ -f $CH_ROAMING_0_CONFIG_tmp ] && mv $CH_ROAMING_0_CONFIG_tmp $CH_ROAMING_0_CONFIG_org
			[ -f $CH_ROAMING_1_CONFIG_tmp ] && mv $CH_ROAMING_1_CONFIG_tmp $CH_ROAMING_1_CONFIG_org
			apply_config_new_4_commit
			clean_config_new
			uci commit

			echo ; echo "[$aHostname].... System Reboot Now!!"
			reboot
			while : ; do
				sleep 1
				echo -n "."
			done
		fi
		;;

	0JustREBOOT)
		textinput \
			 "===============> ReBOOT Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no]\n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
		  clear
		  echo ; echo "[$aHostname].... System Reboot Now!!"
		  reboot -f
		  while : ; do
			sleep 1
			echo -n "."
		  done
		fi
		;;

	# *)
	#	rm $tempfile >/dev/null 2>/dev/null
	#	exit 0
	#	;;

	esac

done

sync

rm $tempfile >/dev/null 2>/dev/null
exit 0

