#!/bin/sh
# (C) 2020 DASAN InfoTek,
#           leesy@DSI
##
. common

local save_default_item=$default_item
default_item=""

cWiFiIndex=$1
if [ "$cWiFiIndex" = "0" ]; then
	cWiFiIndexStr="First"
elif [ "$cWiFiIndex" = "1" ]; then
	cWiFiIndexStr="Second"
else
	cWiFiIndexStr="Unknown"
fi

Freq24TBL="\
auto\n\
2.4G = 2.412(1) 2.417(2) 2.422(3) 2.427(4) 2.432(5) 2.437(6) 2.442(7)\n\
       2.447(8) 2.452(9) 2.457(10) 2.462(11) 2.467(12) 2.472(13)\n"

Freq5TBL="\
auto\n\
5.xG = 5.180(36) 5.200(40) 5.220(44) 5.240(48)\n\
       5.745(149) 5.765(153) 5.785(157) 5.805(161)"

while : ; do

	readNewOrg_System
	readNewOrg_Network
	readNewOrg_Wifi $cWiFiIndex

	inputvar=""

	if [ "$cWdisabled" = "1" ]; then
		menuinput "$cWiFiIndexStr WiFi Configure" \
			'"1WiFi_Mode"   "WiFi disable/AP/ST/WDS __________($cWstat)"
			"X_ExitCancel"  "Exit or Cancel to upper Menu"' \
			"$default_item"
	elif [ "$cWencr" = "none" ]; then
		menuinput "$cWiFiIndexStr WiFi Configure" \
			'"1WiFi_Mode"   "WiFi disable/AP/ST/WDS __________($cWstat)"
			"2WiFi_Band"    "WiFi Band _______________________($cWband GHz)"
			"3WiFi_Freq"    "WiFi Freq _______________________($cWfreq GHz)"
			"4WiFi_eSSID"   "WiFi eSSID/Wireless-Name ________($cWssid)"
			"5WiFi_InLimit" "WiFi Station inactivity limit ___($cWinlimit sec(s))"
			"6WiFi_EncUSE"  "WiFi Encription [none/wep/psk2] _($cWencr)"
			"X_ExitCancel"  "Exit or Cancel to upper Menu"' \
			"$default_item"
	else
		menuinput "$cWiFiIndexStr WiFi Configure" \
			'"1WiFi_Mode"   "WiFi disable/AP/ST/WDS __________($cWstat)"
			"2WiFi_Band"    "WiFi Band _______________________($cWband GHz)"
			"3WiFi_Freq"    "WiFi Freq _______________________($cWfreq GHz)"
			"4WiFi_eSSID"   "WiFi eSSID/Wireless-Name ________($cWssid)"
			"5WiFi_InLimit" "WiFi Station inactivity limit ___($cWinlimit sec(s))"
			"6WiFi_EncUSE"  "WiFi Encription [none/wep/psk2] _($cWencr)"
			"7WiFi_EncKEY"  "WiFi Encription [Key Code] ______($cWkey)"
			"X_ExitCancel"  "Exit or Cancel to upper Menu"' \
			"$default_item"
	fi

	default_item=$inputvar

	case $inputvar in

	1WiFi_Mode)
		inputvar=$cWstat
		errormsg=""
		while :; do
			textinput \
				 "Please enter WiFi Mode [Disable/AP/APW/ST/STW]\n\n"$(
				)"Examples:\n"$(
	 			)" ex1)Disable  ex2)AP  ex3)APW - AP with WDS\n"$(
	 			)" ex4)ST  ex5)STW - Station with WDS\n"$(
				)"\n\Z1$errormsg\Z0\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWstat" ] && break
			# Check input string is one of WiFi Mode
			if [ "$inputvar" = "Disable" ]; then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].disabled="1"
				break
			elif [ "$inputvar" = "AP" ]; then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].disabled="0"
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].wds="0"
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].mode="ap"
				break
			elif [ "$inputvar" = "APW" ]; then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].disabled="0"
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].wds="1"
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].mode="ap"
				break
			elif [ "$inputvar" = "ST" ]; then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].disabled="0"
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].wds="0"
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].mode="sta"
				break
			elif [ "$inputvar" = "STW" ]; then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].disabled="0"
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].wds="1"
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].mode="sta"
				break
			fi
			errormsg="Check input value is WiFi mode!"
		done
		;;

	2WiFi_Band)
		inputvar=$cWband
		errormsg=""
		while :; do
			textinput \
				 "Please enter WiFi Band [2.4/5]GHz\n\n"$(
				)"Examples:\n"$(
	 			)" ex1)2.4  ex2)5\n"$(
				)"\n\Z1$errormsg\Z0\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWband" ] && break
			# Check input string is one of WiFi Mode
			if [ "$inputvar" = "2.4" ]; then
				add_config_new_set_cmd wireless.radio$cWiFiIndex.hwmode="11g"
				add_config_new_set_cmd wireless.radio$cWiFiIndex.channel="auto"
				break
			elif [ "$inputvar" = "5" ]; then
				add_config_new_set_cmd wireless.radio$cWiFiIndex.hwmode="11a"
				add_config_new_set_cmd wireless.radio$cWiFiIndex.channel="auto"
				break
			fi
			errormsg="Check input value is WiFi Band!"
		done
		;;

	3WiFi_Freq)
		[ "$cWband" = "2.4" ] && FreqTBL=$Freq24TBL || FreqTBL=$Freq5TBL
		inputvar=$cWfreq
		errormsg=""
		while :; do
			textinput \
				 "Please enter Running-Frequency... with N.NNN GHz\n\n"$(
				)"Examples:\n"$(
				)"$FreqTBL\n"$(
				)"\n\Z1$errormsg\Z0\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWfreq" ] && break
			# Check input string is not null
			if [ -n "$inputvar" ]; then
				if [ "$inputvar" = "auto" ]; then
					add_config_new_set_cmd wireless.radio$cWiFiIndex.channel="$inputvar"
					break
				else
				# Check input string is one of FreqTBL
					if [ "$inputvar" = "$(echo "$FreqTBL" | grep -o -E -m1 "( $inputvar\([0-9]*\))" | cut -d' ' -f2 | cut -d'(' -f1)" ]; then
						add_config_new_set_cmd wireless.radio$cWiFiIndex.channel="$(echo "$FreqTBL" | grep -o -E -m1 "( $inputvar\([0-9]*\))" | cut -d'(' -f2 | cut -d')' -f1)"
						break
					fi
				fi
			fi
			errormsg="Check input is one of Freq table!"
		done
		;;

	4WiFi_eSSID)
		inputvar=$cWssid
		errormsg=""
		while :; do
			textinput \
				 "Please enter AP SSID/Name ...\n\n"$(
				)"Examples: must input less and equal than 4 chars\n"$(
	 			)" ex1)AP01  ex2)APnn\n"$(
				)"\n\Z1$errormsg\Z0\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWssid" ] && break
			# Check input string is not null and less or equal than 4 chars
			if ([ -n "$inputvar" ] && [ ${#inputvar} -le 4 ]); then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].ssid="$inputvar"
				break
			fi
			errormsg="Check input value is less or equal than 4 chars SSID !"
		done
		;;

	5WiFi_InLimit)
		inputvar=$cWinlimit
		errormsg=""
		while :; do
			textinput \
				"Please enter Station inactivity limit in seconds(> 0)\n\n"$(
				)"Examples:\n"$(
				)" 10  20  30  40  50\n"$(
				)"\n\Z1$errormsg\Z0\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWinlimit" ] && break
			# Check string greater than zero
			if ([ -n "$inputvar" ] && [ $inputvar -gt 0 ]); then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].max_inactivity="$inputvar"
				break
			fi
			errormsg="Check input value is greater than 0!"
		done
		;;

	6WiFi_EncUSE)
		inputvar=$cWencr
		errormsg=""
		while :; do
			textinput \
				 "Please enter WiFi Encription Type [none/wep/psk2]\n\n"$(
				)"Examples:\n"$(
	 			)" ex1)none  ex2)wep-open  ex3)psk2+ccmp\n"$(
				)"\n\Z1$errormsg\Z0\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWencr" ] && break
			# Check encryption types
			if ([ -z "$inputvar" ] || [ "$inputvar" = "none" ]); then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].encryption="none"
				break
			elif [ "$inputvar" = "wep-open" ]; then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].encryption="wep-open"
				break
			elif [ "$inputvar" = "psk2+ccmp" ]; then
				add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].encryption="psk2+ccmp"
				break
			fi
			errormsg="Check input value is one of encryption type!"
		done
		;;

	7WiFi_EncKEY)
		inputvar=$cWkey
		errormsg=""
		while :; do
			if [ "$cWencr" = "psk2+ccmp" ] ; then
				textinput \
					 "Please enter Wireless LAN Encription-Key-Code...\n\n"$(
					)"Examples: must input greater or equal than 8 chars\n"$(
	 				)" ex1)12345678  ex2)1234567890  ex2)1234567890123\n"$(
					)"\n\Z1$errormsg\Z0\n" \
					"$inputvar"
				retval=$?
				# Check return error
				[ $retval -ne 0 ] && break
				# Check changed
				[ "$inputvar" = "$cWencr" ] && break
				# Check input string is not null
				if ([ -n "$inputvar" ] && [ ${#inputvar} -ge 8 ]); then
					add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].key="$inputvar"
					break
				fi
				errormsg="Check input key code and size is greater or equal than 8 chars!"
			else # elif [ "$cWencr" = "wep-open" ] ; then
				textinput \
					 "Please enter Wireless LAN Encription-Key-Code...\n\n"$(
					)"Examples: must input 5 chars or 13 chars\n"$(
	 				)" ex1)12345 ex2)1234567890123 ex3)string13chars\n"$(
					)"\n\Z1$errormsg\Z0\n" \
					"$inputvar"
				retval=$?
				# Check return error
				[ $retval -ne 0 ] && break
				# Check changed
				[ "$inputvar" = "$cWencr" ] && break
				# Check input string is not null
				if ([ -n "$inputvar" ] && ([ ${#inputvar} -eq 5 ] || [ ${#inputvar} -eq 13 ])); then
					add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].key="1"
					add_config_new_set_cmd wireless.@wifi-iface[$cWiFiIndex].key1="s:$inputvar"
					break
				fi
				errormsg="Check input key code and size is 5 or 13 chars!"
			fi
		done
		;;

	timeout)
		;;

	X_ExitCancel | *)
		rm $tempfile >/dev/null 2>/dev/null
		default_item=$save_default_item
		exit 0
		;;

	esac
done
