#!/bin/sh
# (C) 2020 DASAN InfoTek,
#           leesy@DSI
##
. common

local save_default_item=$default_item
default_item=""

while : ; do

	readNewOrg_System
	readNewOrg_Network

	inputvar=""

	menuinput "LAN Configure" \
		'"1eLAN_IPaddr" "LAN IP Address ________($cLip)"
		"2eLAN_IPmask"  "LAN IP Subnet Mask ____($cLmask)"
		"X_ExitCancel"  "Exit or Cancel to upper Menu"' \
		"$default_item"

	default_item=$inputvar

	case $inputvar in

	1eLAN_IPaddr)
		inputvar=$cLip
		errormsg=""
		while :; do
			textinput \
				 "Please enter LAN IP Address ...\n\n"$(
				)"Examples:\n"$(
				)" 10.1.123.1  168.126.0.129\n"$(
				)"\n\Z1$errormsg\Z0\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cLip" ] && break
			# Check valid IP v4
			if isValidIPv4 "$inputvar"; then
				add_config_new_set_cmd network.lan.ipaddr="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	2eLAN_IPmask)
		inputvar=$cLmask
		errormsg=""
		while :; do
			textinput \
				 "Please enter LAN IP Subnet Mask ...\n\n"$(
				)"Examples:\n"$(
				)" 255.255.255.0 255.255.255.128\n"$(
				)"\n\Z1$errormsg\Z0\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cLmask" ] && break
			# Check valid IP v4
			if isValidIPv4 "$inputvar"; then
				add_config_new_set_cmd network.lan.netmask="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	timeout)
		;;

	X_ExitCancel | *)
		rm $tempfile >/dev/null 2>/dev/null
		default_item=$save_default_item
		exit 0
		;;

	esac
done
