#!/bin/sh
#
#####################################################################
##
##      DWS4000 LCD_Mon for Chaos Calmer 15.05.1 @linux3.18
##
##            Copyright 2019, by Dasan InfoTek Co.,
##
##                         ...leesy...
##
#####################################################################

iw phy0 info > /tmp/dwsLCD_phy0

iface=wlan0
SerialPort=/dev/ttyUSB0
SendErrorPipe="2> /dev/null"

readCFG() {
	cWssid=$(uci -q get wireless.@wifi-iface[0].ssid)
	#cWencr=$(uci -q get wireless.@wifi-iface[0].encryption)
	#cWkey=$(uci -q get wireless.@wifi-iface[0].key)

	cWip=$(uci -q get network.wlan.ipaddr)
	#cWmask=$(uci -q get network.wlan.netmask)
	#cWgway=$(uci -q get network.wlan.gateway)
	#cWdns=$(uci -q get network.wlan.dns)

	rFreq=$(grep -E -m1 "(\* .... MHz \[$(uci -q get wireless.radio0.channel)\])" /tmp/dwsLCD_phy0 | \
			awk '{print $2}' | \
			sed -e "s/\([0-9]\)\([0-9]*\)/\1\.\2/")

	iwinfo $iface info 2> /dev/null > /tmp/dwsLCD_$iface
	##
	rSNR=$(grep Link /tmp/dwsLCD_$iface | awk '{print $6}' | cut -d'/' -f1)
	([ -z "$rSNR" ] || [ "$rSNR" = "unknown" ]) && rSNR=0

	rAP=$(grep Access /tmp/dwsLCD_$iface | awk '{ print $3 }')
	if [ -z "$rAP" ] || [ "$rAP" = "00:00:00:00:00:00" ] ; then
		rAP="Not-AP"
	else
		rAP=$(echo $rAP | cut -c12-)
	fi

	##
	#rSSID=$(grep SSID /tmp/dwsLCD_$iface | awk '{print $3" "$4}')

	upTime=$(uptime | cut -c2- | cut -d',' -f1)
	upTime=$(echo "$upTime        " | cut -c -20)

	#rDATE=$(date +%Y%m%e)
	#rDATE="$rDATE $upTime"
	#rDATE=$(echo "$rDATE" | sed 's/^ *//g' | cut -c -20)
}

legacyLCDInit() {
	serial_send $SerialPort "\x1B\x43" $SendErrorPipe
}

cfaLCDInit() {
	### Init CFA LCD
	## Set keypad backlight off
	cfa_send $SerialPort "\x0e\d002\d100\d000" $SendErrorPipe
	## Display splash strings
	cfa_send $SerialPort "\x1f\d022\d000\d000DASAN InfoTek       " $SendErrorPipe
	cfa_send $SerialPort "\x1f\d022\d000\d001                    " $SendErrorPipe
	cfa_send $SerialPort "\x1f\d022\d000\d002                    " $SendErrorPipe
	cfa_send $SerialPort "\x1f\d022\d000\d003     www.dsintek.com" $SendErrorPipe
	## Store current state as boot state
	cfa_send $SerialPort "\x04\d000" $SendErrorPipe
}

### Start of main script

### Check and wait USB serial character device file exists
while [ ! -c $SerialPort ] ; do
	sleep 1 # wait 1sec
	echo "Check inserted the USB serial LCD!"
done
USB_SERIAL_DEV_EXIST=1
sleep 1 # wait 1sec

### Check CFA LCD
## Ping LCD
cfa_send $SerialPort "\x00\d000" $SendErrorPipe
if [ $? -eq 0 ] ; then
	CFA_DETECTED=1
	echo "Detected CFA LCD!"
else
	CFA_DETECTED=0
	echo "Detected legacy LCD!"
fi

# Init LCD
if [ $CFA_DETECTED -eq 1 ] ; then
	cfaLCDInit
else
	legacyLCDInit
fi

# infinite while loop
while : ; do
	sleep 1

	### Check and wait USB serial character device file exists
	while [ ! -c $SerialPort ] ; do
		USB_SERIAL_DEV_EXIST=0
		sleep 1 # wait 1sec
		echo "Check inserted the USB serial LCD!"
	done

	if [ $USB_SERIAL_DEV_EXIST -eq 0 ] ; then
		USB_SERIAL_DEV_EXIST=1
		sleep 1 # wait 1sec
		### Check CFA LCD
		## Ping LCD
		cfa_send $SerialPort "\x00\d000" $SendErrorPipe
		if [ $? -eq 0 ] ; then
			CFA_DETECTED=1
			echo "Detected CFA LCD!"
		else
			CFA_DETECTED=0
			echo "Detected legacy LCD!"
		fi
		# echo "CFA_DETECTED=$CFA_DETECTED"

		# Init LCD
		if [ $CFA_DETECTED -eq 1 ] ; then
			cfaLCDInit
		else
			legacyLCDInit
		fi
	fi

	readCFG
	###

	if [ $CFA_DETECTED -eq 1 ] ; then
		### Locate 0,0
		cfa_send $SerialPort "\x1f\d022\d000\d000IP:$cWip                    " $SendErrorPipe
		### Locate 0,1
		cfa_send $SerialPort "\x1f\d016\d000\d001ID:$cWssid              " $SendErrorPipe
		### Locate 14,1
		cfa_send $SerialPort "\x1f\d008\d014\d001$rAP      " $SendErrorPipe
		### Locate 0,2
		cfa_send $SerialPort "\x1f\d022\d000\d002FQ:$rFreq SNR:$rSNR                    " $SendErrorPipe
		### Locate 0,3
		cfa_send $SerialPort "\x1f\d022\d000\d003$upTime                    " $SendErrorPipe
	else
		### Locate 0,0
		serial_send $SerialPort "\x1B\x4C\x00\x00IP:$cWip" $SendErrorPipe
		### Locate 0,1
		serial_send $SerialPort "\x1B\x4C\x00\x01ID:$cWssid " $SendErrorPipe
		### Locate 14,1
		serial_send $SerialPort "\x1B\x4C\x0E\x01$rAP" $SendErrorPipe
		### Locate 0,2
		serial_send $SerialPort "\x1B\x4C\x00\x02FQ:$rFreq SNR:$rSNR " $SendErrorPipe
		### Locate 0,3
		serial_send $SerialPort "\x1B\x4C\x00\x03$upTime" $SendErrorPipe
	fi
done

### END of Main script ###
