#!/bin/sh
# (C) 2019 DASAN InfoTek,
#           leesy@DSI
##
. wCommon

DIALOG=${DIALOG=dialog}

tempfile="/tmp/DSWconfig_wifi$$"
trap "rm -f $tempfile; exit" 0 1 2 5 15

textinput() {
	$DIALOG \
	--ascii-lines --title "INPUT BOX" --clear \
	--inputbox "$1" 20 76 "$2" 2> $tempfile

	retval=$?

	case $retval in
	0)
		inputvar=`cat $tempfile`;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}

menuinput() {

	menucmd=`cat <<END    
$DIALOG --ascii-lines --clear --cr-wrap --title "[[ Wireless LAN Configurations ]]" \
	--menu "$3\nStat=[ SNR:$rSNR Freq:$rFreq AP=$rAP ] \
	\n$rDATE >> Please menu select: \n" 22 76 12 \
	$1 \
	2> $tempfile
END
`
eval $menucmd

	retval=$?

	case $retval in
	0)
		inputvar=`cat $tempfile`
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}


########################## begin

rm -f $tempfile

mchoice="";


while : ; do

	inputvar=""

	readCFG
	#######

	readWIFI
	#######

	readDATE
	#######

	menuinput '"ReviewSNR_AP"  "Status Review .... Enter!"
		"1Wlan_eSSID"   "WLAN eSSID/Wireless-Name ________($cWssid)"
		"2Wlan_EncUSE"  "WLAN Encription [none/wep/psk2] _($cWencr)"
		"3Wlan_EncKEY"  "WLAN Encription [Key Code] ______($cWkey)"
		"DWSroaming"    ">> DWS4000 Frequency & Roaming Configure <<"
		"X_ExitCancel"  "Exit or Cancel to upper Menu"'

	case $inputvar in

	ReviewSNR_AP)
		;;

	1Wlan_eSSID)
	        textinput "Please enter Wireless LAN ESSID/Name ... \n\n \
	Examples: \n ex1)WLAN001  ex2)SR-123 \n" \
		"$cWssid"
		uci set wireless.@wifi-iface[0].ssid="$inputvar"
		;;

	2Wlan_EncUSE)
	        textinput "Please enter Wireless LAN Encription Type [none/wep] \n\n \
	Examples: \n ex1)none  ex2)wep-open ex3)psk2+ccmp\n" \
		"$cWencr"
		if [ "$inputvar" = "psk2+ccmp" ] ; then
			uci set wireless.@wifi-iface[0].encryption="psk2+ccmp"
		elif [ "$inputvar" = "wep-open" ] ; then
			uci set wireless.@wifi-iface[0].encryption="wep-open"
		else
			uci set wireless.@wifi-iface[0].encryption="none"
		fi
		;;

	3Wlan_EncKEY)
		if [ "$cWencr" = "psk2+ccmp" ] ; then
			textinput "Please enter Wireless LAN Encription-Key-Code... \n\n \
		Examples: must input more and equal than 8 chars \n ex1)12345678 ex2)1234567890123 \n" \
			"$cWkey"
			uci set wireless.@wifi-iface[0].key="$inputvar"
		else
			textinput "Please enter Wireless LAN Encription-Key-Code... \n\n \
		Examples: \n ex1)s:1234567890123 ex2)s:string13chars \n" \
			"$cWkey"
			uci set wireless.@wifi-iface[0].key="1"
			uci set wireless.@wifi-iface[0].key1="$inputvar"
		fi
		;;

	DWSroaming)
		/etc/dws4000/wrsetup
		;;

	X_ExitCancel | *)
		rm $tempfile >/dev/null 2>/dev/null
		exit 0
		;;

	esac

done

