#!/bin/sh
# (C) 2019 DASAN InfoTek,
#           leesy@DSI
##
. wCommon

DIALOG=${DIALOG=dialog}

tempfile="/tmp/DSWconfig_NET$$"
trap "rm -f $tempfile; exit" 0 1 2 5 15

textinput() {
	$DIALOG \
	--ascii-lines --title "INPUT BOX" --clear \
	--inputbox "$1" 20 76 "$2" 2> $tempfile

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi

	return $retval
}

menuinput() {

	menucmd=$(cat <<END    
$DIALOG --ascii-lines --clear --cr-wrap --title "[[ Network IP Configurations ]]" \
	--menu "$3\nStat=[ SNR:$rSNR Freq:$rFreq AP=$rAP ]  Please menu select: \n" 22 76 13 \
	$1 \
	2> $tempfile
END
)

eval $menucmd

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}


########################## begin

rm -f $tempfile

mchoice="";


while : ; do

	inputvar=""

	readCFG
	#######

	readNET
	#######

	menuinput '"1Wlan_IPaddr"  "WLAN IP Address _____________($cWip)"
		"2Wlan_IPmask"  "WLAN IP Subnet Mask _________($cWmask)"
		"3Wlan_Gateway" "Gateway/Router IP Address ___($cWgway)"
		"4eLAN_IPaddr"  "Wired-LAN IP Address ________($cLip)"
		"5eLAN_IPmask"  "Wired-LAN IP Subnet Mask ____($cLmask)"
		"6Wlan_IPdns"   "DNS Server IP Address _______($cWdns)"
		"7Wlan_IPslog"  "Syslog Server IP Address ____($cSlogip)"'

	case $inputvar in

	1Wlan_IPaddr)
		inputvar=$cWip
		errormsg=""
		while :; do
			textinput \
				 "Please enter Wireless LAN IP Address ...\n\n"$(
				)"Examples:\n"$(
				)" 192.168.0.127  10.1.1.127 \n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWip" ] && break
			# Check valid IP v4
			if isValidIPv4 "$inputvar"; then
				uci set network.wlan.ipaddr="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	2Wlan_IPmask)
		inputvar=$cWmask
		errormsg=""
		while :; do
			textinput \
				 "Please enter Wireless LAN IP Subnet Mask ...\n\n"$(
				)"Examples:\n"$(
				)" 255.255.0.0  255.255.255.0\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWmask" ] && break
			# Check valid IP v4
			if isValidIPv4 "$inputvar"; then
				uci set network.wlan.netmask="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	3Wlan_Gateway)
		inputvar=$cWgway
		errormsg=""
		while :; do
			textinput \
				 "Please enter Network Gateway/Router IP Address\n\n"$(
				)"Examples: can blank\n"$(
				)" 10.1.1.1  192.168.0.1 \n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWgway" ] && break
			# Check string null or valid IP v4
			if [ -z "$inputvar" ] || isValidIPv4 "$inputvar"; then
				uci set network.wlan.gateway="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	4eLAN_IPaddr)
		inputvar=$cLip
		errormsg=""
		while :; do
			textinput \
				 "Please enter Wired Ethernet IP Address ...\n\n"$(
				)"Examples:\n"$(
				)" 10.1.123.1  168.126.0.129\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cLip" ] && break
			# Check valid IP v4
			if isValidIPv4 "$inputvar"; then
				uci set network.lan.ipaddr="$inputvar"
				###
				eMAC=$(/sbin/ifconfig | grep "eth0" | tr -s " " | cut -d " " -f5)
				echo "$eMAC $inputvar" > /etc/ethers
				###
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	5eLAN_IPmask)
		inputvar=$cLmask
		errormsg=""
		while :; do
			textinput \
				 "Please enter Wired Ethernet IP Subnet Mask ...\n\n"$(
				)"Examples:\n"$(
				)" 255.255.255.0 255.255.255.128\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cLmask" ] && break
			# Check valid IP v4
			if isValidIPv4 "$inputvar"; then
				uci set network.lan.netmask="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	6Wlan_IPdns)
		inputvar=$cWdns
		errormsg=""
		while :; do
			textinput \
				 "Please enter Network DNS Server IP Address ...\n\n"$(
				)"Examples: can blank\n"$(
				)" 168.126.63.1  168.126.63.1\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWdns" ] && break
			# Check string null or valid IP v4
			if [ -z "$inputvar" ] || isValidIPv4 "$inputvar"; then
				uci set network.wlan.dns="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	7Wlan_IPslog)
		inputvar=$cSlogip
		errormsg=""
		while :; do
			textinput \
				 "Please enter Network Syslog Server IP Address\n\n"$(
				)"Examples: can blank\n"$(
				)" 10.1.1.13  168.126.0.111\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cSlogip" ] && break
			# Check string null or valid IP v4
			if [ -z "$inputvar" ] || isValidIPv4 "$inputvar"; then
				uci set system.@system[0].log_ip="$inputvar"
				break
			fi
			errormsg="Check input value is IP v4 format!"
		done
		;;

	*)
		rm $tempfile >/dev/null 2>/dev/null
		exit 0
		;;

	esac
done
