#!/bin/sh
# (C) 2019 DASAN InfoTek,
#           leesy@DSI
##
. wCommon

DIALOG=${DIALOG=dialog}

CONFIGPATH_org="/etc/dws4000/wroaming.config"
CONFIG_UPDATED="/tmp/.wroaming.config.updated"

tempfile="/tmp/DSWconfig_main$$"
trap "rm -f $tempfile; exit" 0 1 2 5 15

textinput() {
	$DIALOG \
	--ascii-lines --title "INPUT BOX" --clear \
	--inputbox "$1" 20 76 "$2" 2> $tempfile

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}

menuinput() {

	menucmd=$(cat <<END    
$DIALOG --ascii-lines --clear --cr-wrap --title "[ $ModelName V4.32 Configurations 2019@DSi ]" \
	--menu "$3\nWLAN=[ $rHWMODE ESSID:$rSSID ] \nStat=[ SNR:$rSNR Freq:$rFreq AP=$rAP ] \
	\n$rDATE >> Please menu select: \n" 22 76 11 \
	$1 \
	2> $tempfile
END
)

eval $menucmd

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}


########################## begin

rm -f $tempfile

mchoice="";

while : ; do

	sync
	####

	inputvar=""

	readModelName

	readCFG
	#######

	readDATE
	#######

	menuinput '"ReviewSTATs"  "Status Review .... Enter!"
		"1TestRoaming"   "** $ModelName Redundant-Roaming TEST! **"
		"2NetIPconfig"   ">> Network TCP/IP Address _____Configure <<"
		"3WLAN_config"   ">> Wireless LAN SSID & Secure _Configure <<"
		"4DWSroaming"    ">> $ModelName Frequency & Roaming Configure <<"
		"5SaveCommit"    "Commit All Configure Save!"
		"6SaveReboot"    "Save(commit) & ReBOOT....!"
		"7JustREBOOT"	 "==============>ReBOOT....!"'

	case $inputvar in

	ReviewSTATs)
		;;

	1TestRoaming)
		textinput \
			 "$ModelName Redundant/Roaming TEST... Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [Y]=Roaming/[N]=Review\n" \
			"N"
		if [ "$inputvar" = "Y" ] ; then
			clear
			echo ; echo "[$ModelName]... Roaming New-Frequency Now!!"
			touch /tmp/.force_Roaming
			sleep 1

			local TestRoamingTimer=0
			local TestRoamingTimeout=30 # 30secs
			while [ -e /tmp/.force_Roaming ] ; do
				sleep 1
				TestRoamingTimer=$((TestRoamingTimer+1))
				[ $TestRoamingTimer -ge $TestRoamingTimeout ] && break
			done

			if [ -e /tmp/.force_Roaming ] ; then
				rm -f /tmp/.force_Roaming
				echo ; echo "[$ModelName]... Error! Roaming New-Frequency!"
			else
				echo ; echo "[$ModelName]... Success! roam New-Frequency."
			fi

			#/etc/dws4000/nfreq
			#sleep 2  ###5
			#iwinfo $iface info
			sleep 1
		fi
		;;

	2NetIPconfig)
		/etc/dws4000/wNETsetup
		;;

	3WLAN_config)
		/etc/dws4000/wWIFIsetup
		;;

	4DWSroaming)
		/etc/dws4000/wrsetup
		;;

	5SaveCommit)
		textinput \
			 "Commit All Configures & Save Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no] \n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
			clear
			echo ; echo "[$ModelName].... Commit All Configures Save Now!!"
			###################################################################
			if [ `uci -q get wireless.radio0.txpower` ] ; then
				uci delete wireless.radio0.txpower
				echo ; echo "[$ModelName].... Wlan-TxPower Option Deleted!!"
				#sleep 1
			fi
			###################################################################
			if [ -e $CONFIG_UPDATED ] ;  then
				runFreqGHz1=$(grep $iface"_RunFreq1" $CONFIGPATH_org | sed 's/.*="\(.*\)"/\1/')
				runFreqMHz1=$(echo "$runFreqGHz1*1000/1" | bc) # to MHz
				#echo "Freq1 = $runFreqGHz1($runFreqMHz1)"
				channel=$(getChannel $runFreqMHz1)
				#echo "channel = $channel"
				uci set wireless.radio0.channel=$channel
				rm -f $CONFIG_UPDATED
				echo ; echo "[$ModelName].... Wlan-Frequency Updated!!"
				#sleep 1
			fi
			###################################################################
			uci commit
			#sleep 1
			/etc/init.d/DWSroaming stop 2>/dev/null
			echo ; echo "[$ModelName].... All Interface Restart...!!"
			/etc/init.d/network restart 2>/dev/null
			sleep 1
			echo ; echo "[$ModelName].... DWSroaming Start...!!"
			/etc/init.d/DWSroaming start 2>/dev/null
			sleep 1
		fi
		;;

	6SaveReboot)
		textinput \
			 "Commit All Configures & ReBOOT Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no]\n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
			clear
			echo ; echo "[$ModelName].... Commit All Configures Now!!"
			###################################################################
			if [ `uci -q get wireless.radio0.txpower` ] ; then
				uci delete wireless.radio0.txpower
				echo ; echo "[$ModelName].... Wlan-TxPower Option Deleted!!"
				#sleep 1
			fi
			###################################################################
			if [ -e $CONFIG_UPDATED ] ;  then
				runFreqGHz1=$(grep $iface"_RunFreq1" $CONFIGPATH_org | sed 's/.*="\(.*\)"/\1/')
				runFreqMHz1=$(echo "$runFreqGHz1*1000/1" | bc) # to MHz
				#echo "Freq1 = $runFreqGHz1($runFreqMHz1)"
				channel=$(getChannel $runFreqMHz1)
				#echo "channel = $channel"
				uci set wireless.radio0.channel=$channel
				rm -f $CONFIG_UPDATED
				echo ; echo "[$ModelName].... Wlan-Frequency Updated!!"
				#sleep 1
			fi
			###################################################################
			uci commit
			#sleep 1
			#/etc/init.d/collectd stop
			#sync
			echo ; echo "[$ModelName].... All Interface Restart...!!"
			#sleep 1
			sync
			##clear
			echo ; echo "[$ModelName].... System Reboot Now!!"
			reboot
			while : ; do
				sleep 1
				echo -n "."
			done
		fi
		;;

	7JustREBOOT)
		textinput \
			 "===============> ReBOOT Now?? [Yes/No]\n\n"$(
			)"Please Enter:\n"$(
			)" [YES]/[no]\n" \
			"NO"
		if [ "$inputvar" = "YES" ] ; then
		  clear
		  echo ; echo "[$ModelName].... System Reboot Now!!"
		  reboot -f
		  while : ; do
			sleep 1
			echo -n "."
		  done
		fi
		;;

	# *)
	#	rm $tempfile >/dev/null 2>/dev/null
	#	exit 0
	#	;;

	esac

done

sync

rm $tempfile >/dev/null 2>/dev/null
exit 0

