#!/bin/sh
# (C) 2019 DASAN InfoTek,
#           leesy@DSI
##
. wCommon

DIALOG=${DIALOG=dialog}

tempfile="/tmp/DSWconfig_wifi$$"
trap "rm -f $tempfile; exit" 0 1 2 5 15

textinput() {
	$DIALOG \
	--ascii-lines --title "INPUT BOX" --clear \
	--inputbox "$1" 20 76 "$2" 2> $tempfile

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi

	return $retval
}

menuinput() {

	menucmd=$(cat <<END    
$DIALOG --ascii-lines --clear --cr-wrap --title "[[ Wireless LAN Configurations ]]" \
	--menu "$3\nStat=[ SNR:$rSNR Freq:$rFreq AP=$rAP ] \
	\n$rDATE >> Please menu select: \n" 22 76 12 \
	$1 \
	2> $tempfile
END
)

eval $menucmd

	retval=$?

	case $retval in
	0)
		inputvar=$(cat $tempfile)
		;;
	1)
		inputvar=$2
		;;
	255)
		inputvar=$2
		;;
	esac

	if [ "$inputvar" = "--" ] ; then inputvar="" ; fi
}


########################## begin

rm -f $tempfile

mchoice="";

while : ; do

	inputvar=""

	readModelName

	readCFG
	#######

	readWIFI
	#######

	readDATE
	#######

	if [ "$cWencr" = "none" ] ; then
		menuinput '"ReviewSNR_AP"  "Status Review .... Enter!"
			"1Wlan_eSSID"   "WLAN eSSID/Wireless-Name ________($cWssid)"
			"2Wlan_EncUSE"  "WLAN Encription [none/wep/psk2] _($cWencr)"
			"DWSroaming"    ">> $ModelName Frequency & Roaming Configure <<"
			"X_ExitCancel"  "Exit or Cancel to upper Menu"'
	else
		menuinput '"ReviewSNR_AP"  "Status Review .... Enter!"
			"1Wlan_eSSID"   "WLAN eSSID/Wireless-Name ________($cWssid)"
			"2Wlan_EncUSE"  "WLAN Encription [none/wep/psk2] _($cWencr)"
			"3Wlan_EncKEY"  "WLAN Encription [Key Code] ______($cWkey)"
			"DWSroaming"    ">> $ModelName Frequency & Roaming Configure <<"
			"X_ExitCancel"  "Exit or Cancel to upper Menu"'
	fi

	case $inputvar in

	ReviewSNR_AP)
		;;

	1Wlan_eSSID)
		inputvar=$cWssid
		errormsg=""
		while :; do
			textinput \
				 "Please enter Wireless LAN ESSID/Name ...\n\n"$(
				)"Examples:\n"$(
	 			)" ex1)WLAN001  ex2)SR-123\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWssid" ] && break
			# Check input string is not null
			if [ -n "$inputvar" ] ; then
				uci set wireless.@wifi-iface[0].ssid="$inputvar"
				break
			fi
			errormsg="Check input value is SSID!"
		done
		;;

	2Wlan_EncUSE)
		inputvar=$cWencr
		errormsg=""
		while :; do
			textinput \
				 "Please enter Wireless LAN Encription Type [none/wep/psk2]\n\n"$(
				)"Examples:\n"$(
	 			)" ex1)none  ex2)wep-open  ex3)psk2+ccmp\n"$(
				)"\n$errormsg\n" \
				"$inputvar"
			retval=$?
			# Check return error
			[ $retval -ne 0 ] && break
			# Check changed
			[ "$inputvar" = "$cWencr" ] && break
			# Check encryption types
			if [ "$inputvar" = "psk2+ccmp" ] ; then
				uci set wireless.@wifi-iface[0].encryption="psk2+ccmp"
				break
			elif [ "$inputvar" = "wep-open" ] ; then
				uci set wireless.@wifi-iface[0].encryption="wep-open"
				break
			elif [ -z "$inputvar" ] || [ "$inputvar" = "none" ] ; then
				uci set wireless.@wifi-iface[0].encryption="none"
				break
			fi
			errormsg="Check input value is one of encryption type!"
		done
		;;

	3Wlan_EncKEY)
		inputvar=$cWkey
		errormsg=""
		while :; do
			if [ "$cWencr" = "psk2+ccmp" ] ; then
				textinput \
					 "Please enter Wireless LAN Encription-Key-Code...\n\n"$(
					)"Examples: must input more and equal than 8 chars\n"$(
	 				)" ex1)12345678  ex2)1234567890123\n"$(
					)"\n$errormsg\n" \
					"$inputvar"
				retval=$?
				# Check return error
				[ $retval -ne 0 ] && break
				# Check changed
				[ "$inputvar" = "$cWencr" ] && break
				# Check input string is not null
				if [ -n "$inputvar" ] ; then
					uci set wireless.@wifi-iface[0].key="$inputvar"
					break
				fi
			else # elif [ "$cWencr" = "wep-open" ] ; then
				textinput \
					 "Please enter Wireless LAN Encription-Key-Code...\n\n"$(
					)"Examples: must input 5 chars or 13 chars\n"$(
	 				)" ex1)12345 ex2)1234567890123 ex3)string13chars\n"$(
					)"\n$errormsg\n" \
					"$inputvar"
				retval=$?
				# Check return error
				[ $retval -ne 0 ] && break
				# Check changed
				[ "$inputvar" = "$cWencr" ] && break
				# Check input string is not null
				if [ -n "$inputvar" ] && ([ ${#inputvar} -eq 5 ] || [ ${#inputvar} -eq 13 ])  ; then
					uci set wireless.@wifi-iface[0].key="1"
					uci set wireless.@wifi-iface[0].key1="s:$inputvar"
					break
				fi
			fi
			errormsg="Check input key code and size is 5 or 13!"
		done
		;;

	DWSroaming)
		/etc/dws4000/wrsetup
		;;

	X_ExitCancel | *)
		rm $tempfile >/dev/null 2>/dev/null
		exit 0
		;;

	esac

done

